layout: stacked #sidebar
style: dark #light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

repositories:
  - Pokefetch
  - manual-alpaca
  - terminal-wallpaper
  - NumberPhile
  - pynux
  - Parallel-KNN

topics:
  - name: Go
    web_url: https://github.com/topics/go
    image_url: images/gopherize-me.png

  - name: Docker
    web_url: https://www.docker.com/
    image_url: images/docker.png

  - name: Kubernetes 
    web_url: https://kubernetes.io/
    image_url: images/kubernetes.png

  - name: TravisCI
    web_url: https://travis-ci.org/
    image_url: images/travisci.png
